
language: cpp

compiler: gcc

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq cmake libavformat-dev libavcodec-dev libavdevice-dev libavfilter-dev libavutil-dev

install:
 - mkdir build && cd build
 - cmake .. && make

