
language: cpp

compiler: gcc

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq cmake libavformat-dev libavcodec-dev libavdevice-dev libavfilter-dev libavutil-dev libswscale-dev libpostproc-dev libv4l-dev

install:
 - mkdir build && cd build
 - cmake .. 

script: make -j2 && cd ..

after_success:
 - export PATH=$PATH:$TRAVIS_BUILD_DIR/bin
 - ./data/mnist/get_mnist.sh
 - transfer_mnist2xml --solver data/mnist/lenet_solver.xml
 - network train --solver data/mnist/lenet_solver.xml
 - transfer_addition --solver data/addition/rnn_solver.xml
 - network train --solver data/addition/rnn_solver.xml


